export type {
  ActorAliasRecord,
  ActorAliasType,
  ActorRecord,
  ActorResolutionRepository,
  ActorType,
  CreateActorInput,
  ResolveActorsDecision,
  ResolveActorsOptions,
  ResolveActorsResult,
  ResolvedActorMention,
  ResolvedAlias,
  ResolvedEmailQuote,
  ResolveParsedDocumentTarget,
  UpsertActorAliasInput,
} from './actor-resolution.js';
export { parseSenderAlias, resolveActors } from './actor-resolution.js';
export type {
  ChunkAndEmbedDecision,
  ChunkAndEmbedOptions,
  ChunkAndEmbedResult,
  ChunkArchiveReason,
  ChunkConfig,
  ChunkEmbeddingRepository,
  ChunkEmbeddingTarget,
  DocumentChunkRecord,
  DocumentRecord,
  EmbeddingProvider,
  PreparedDocumentChunk,
  ReplaceDocumentChunksInput,
  UpsertDocumentInput,
} from './chunk-embedding.js';
export {
  checkEmbeddingProvider,
  chunkAndEmbed,
  createDeterministicEmbeddingProvider,
  createGeminiEmbeddingProvider,
  DEFAULT_CHUNK_CONFIG,
  DEFAULT_DETERMINISTIC_EMBEDDING_MODEL,
  DEFAULT_EMBEDDING_DIMENSIONS,
  DEFAULT_GEMINI_EMBEDDING_MODEL,
  prepareDocumentChunks,
  validateGeminiEmbeddingConfig,
} from './chunk-embedding.js';
export type {
  CollectDecision,
  CollectFixtureOptions,
  CollectFixtureResult,
  CollectionObjectStorage,
  CollectionRepository,
  DataSourceRecord,
  FixtureCandidate,
  LinkDataSourceInput,
  ProjectRecord,
  QueueCandidateInput,
  RawDocumentInput,
  RawDocumentRecord,
} from './collection-pipeline.js';
export {
  collectFixtureSource,
  normalizeSourceId,
  scanFixtureSource,
  shouldCollectCandidate,
} from './collection-pipeline.js';
export type {
  CollectDriveSourceOptions,
  CollectDriveSourceResult,
  DriveCandidate,
  DriveFetcher,
  DriveFileResponse,
  DriveListResponse,
  DriveOwnerResponse,
  DriveRawCandidate,
  DriveRawDocument,
  DriveTextFetcher,
} from './drive-source.js';
export {
  buildDriveRawCandidate,
  collectDriveSource,
  fetchDriveJson,
  fetchDriveText,
  scanDriveDataSource,
} from './drive-source.js';
export type {
  CollectGitHubSourceOptions,
  CollectGitHubSourceResult,
  GitHubCandidate,
  GitHubCommentResponse,
  GitHubDiffFetcher,
  GitHubFetcher,
  GitHubIssueResponse,
  GitHubRawCandidate,
  GitHubRawDocument,
  GitHubReviewResponse,
} from './github-source.js';
export {
  buildGitHubRawCandidate,
  collectGitHubSource,
  fetchGitHubJson,
  fetchGitHubText,
  scanGitHubDataSource,
} from './github-source.js';
export type {
  GraphActorAliasType,
  GraphEdgeInput,
  GraphEdgeType,
  GraphEmailQuoteInput,
  GraphNodeInput,
  GraphRelationActorRecord,
  GraphRelationDocumentRecord,
  GraphRelationProjectRecord,
  GraphRelationsRepository,
  GraphRelationTarget,
  ReplaceEmailQuotesInput,
  StoreGraphRelationDecision,
  StoreGraphRelationsOptions,
  StoreGraphRelationsResult,
} from './graph-relations.js';
export { storeGraphRelations } from './graph-relations.js';
export type {
  ActorMention,
  IngestionFixtureCase,
  ParsedDocument,
  ParsedDocumentType,
  ParsedRelation,
  RawDocumentContract,
  SourceType,
} from './ingestion-fixtures.js';
export {
  loadIngestionFixtureCases,
  parseRawContent,
  parseRawFixture,
  validateParsedDocument,
  validateRawFixtureCase,
} from './ingestion-fixtures.js';
export type {
  HoldReason,
  IngestionQueueStatus,
  MarkFailedInput,
  MarkHeldInput,
  MarkParsedInput,
  ParseObjectStorage,
  ParseProjectRecord,
  ParseQueueTarget,
  ParseRawDecision,
  ParseRawDocumentRecord,
  ParseRawOptions,
  ParseRawResult,
  ParserVersionContract,
  ParserVersionRecord,
  RawIngestStatus,
  RawParseRepository,
} from './raw-parse.js';
export {
  BUILT_IN_PARSER_ARTIFACT,
  BUILT_IN_PARSER_ARTIFACT_HASH,
  defaultBuiltInParserVersion,
  defaultParserContract,
  PARSED_SCHEMA_VERSION,
  parsedStorageUri,
  parseRawDocuments,
  validateParserContract,
} from './raw-parse.js';
export type {
  CollectWebUrlSourceOptions,
  CollectWebUrlSourceResult,
  WebUrlCandidate,
  WebUrlFetcher,
  WebUrlFetchResponse,
  WebUrlRawCandidate,
} from './web-url-source.js';
export {
  buildWebUrlRawCandidate,
  collectWebUrlSource,
  fetchWebUrl,
  scanWebUrlDataSource,
} from './web-url-source.js';
