import assert from 'node:assert/strict';
import test from 'node:test';
import { requiredEnv, validateGraphName } from './cli.ts';

test('requiredEnv returns configured environment values', () => {
  const previous = process.env.PUFU_LENS_TEST_REQUIRED_ENV;
  process.env.PUFU_LENS_TEST_REQUIRED_ENV = 'configured';

  try {
    assert.equal(requiredEnv('PUFU_LENS_TEST_REQUIRED_ENV'), 'configured');
  } finally {
    if (previous === undefined) {
      delete process.env.PUFU_LENS_TEST_REQUIRED_ENV;
    } else {
      process.env.PUFU_LENS_TEST_REQUIRED_ENV = previous;
    }
  }
});

test('requiredEnv rejects missing environment values', () => {
  const previous = process.env.PUFU_LENS_TEST_REQUIRED_ENV;
  delete process.env.PUFU_LENS_TEST_REQUIRED_ENV;

  try {
    assert.throws(
      () => requiredEnv('PUFU_LENS_TEST_REQUIRED_ENV'),
      /PUFU_LENS_TEST_REQUIRED_ENV is required\./,
    );
  } finally {
    if (previous !== undefined) {
      process.env.PUFU_LENS_TEST_REQUIRED_ENV = previous;
    }
  }
});

test('validateGraphName accepts AGE graph names generated by project tenancy', () => {
  assert.equal(validateGraphName('graph_project_123'), 'graph_project_123');
});

test('validateGraphName rejects invalid AGE graph names', () => {
  assert.throws(() => validateGraphName('project_123'), /Invalid AGE graph name/);
  assert.throws(() => validateGraphName('graph_Project'), /Invalid AGE graph name/);
  assert.throws(() => validateGraphName(`graph_${'a'.repeat(60)}`), /Invalid AGE graph name/);
});
