/** Independent synthetic relevance judgments, fixed before collecting provider results (Issue #767). */
export const qualityDocuments = [
  ['cat', '黒猫の飼育記録'],
  ['glass', 'ガラス工芸体験'],
  ['tokyo', '東京都の図書館案内'],
  ['search', '検索品質評価の手順'],
  ['invoice', 'invoice 31415 approved'],
  ['invoice-neighbor', 'invoice 31416 approved'],
  ['invoice-prefix', 'invoice 314150 approved'],
  ['invoice-suffix', 'invoice 931415 approved'],
  ['invoice-short', 'invoice 314 approved'],
  ['release', 'release 12 build 34'],
  ['release-neighbor', 'release 12 build 35'],
  ['release-reverse', 'release 34 build 12'],
  ['release-repeat', 'release 12 build 12'],
  ['ticket', '障害 INC-742 対応済み'],
  ['ticket-neighbor', '障害 INC-743 対応済み'],
  ['ticket-long', '障害 INC-7420 対応済み'],
  ['year', '２０２６年度の検索品質計画'],
  ['year-neighbor', '２０２５年度の検索品質計画'],
  ['decimal', 'version 3.14 released'],
  ['decimal-neighbor', 'version 3.15 released'],
  ['leading-zero', 'batch 007 complete'],
  ['plain-seven', 'batch 7 complete'],
  ['activity', 'ActivityPub federation enabled'],
  ['disabled', 'ActivityPub federation disabled'],
  ['nebula', 'NebulaNote roadmap'],
  ['escape', 'rate 50% x_y C:\\tmp'],
  ['escape-neighbor', 'rate 50X xAy C:/tmp'],
  ['unicode', 'カ\u3099ラスとcafe\u0301 🧑‍💻'],
  ['width', '① ＡＰＩ ﬃ'],
  ['accent', 'naïve résumé'],
  ['url', 'https://example.test/team/repo-name'],
  ['identifier', 'user_id alpha-beta'],
  ['unrelated', '砂漠の植物観察'],
] as const;

export interface QualityCase {
  readonly id: string;
  readonly category: string;
  readonly query: string;
  /** Relevant document IDs, independent of either provider's observed output. */
  readonly relevant: readonly string[];
}

/** Numbers require complete digit runs; ordinary terms require all requested concepts. Typos retain intended relevance. */
export const qualityCases: readonly QualityCase[] = [
  { id: 'ja-one', category: 'japanese-short', query: '猫', relevant: ['cat'] },
  { id: 'ja-two', category: 'japanese-short', query: '黒猫', relevant: ['cat'] },
  { id: 'ja-place', category: 'japanese-short', query: '東京', relevant: ['tokyo'] },
  {
    id: 'ja-search',
    category: 'japanese-short',
    query: '検索',
    relevant: ['search', 'year', 'year-neighbor'],
  },
  { id: 'ja-typo', category: 'typo', query: 'ガラズ', relevant: ['glass', 'unicode'] },
  { id: 'ja-transpose', category: 'typo', query: '検索品評価質', relevant: ['search'] },
  { id: 'latin-typo', category: 'typo', query: 'NebulaNtoe', relevant: ['nebula'] },
  {
    id: 'technical-typo',
    category: 'typo',
    query: 'ActivtyPub',
    relevant: ['activity', 'disabled'],
  },
  { id: 'digits-exact', category: 'numeric', query: '31415', relevant: ['invoice'] },
  { id: 'digits-prefix', category: 'numeric', query: '314', relevant: ['invoice-short'] },
  { id: 'digits-middle', category: 'numeric', query: '1415', relevant: [] },
  { id: 'digits-absent', category: 'numeric', query: '31417', relevant: [] },
  { id: 'digits-natural', category: 'numeric', query: 'invoice 31415', relevant: ['invoice'] },
  { id: 'digits-natural-typo', category: 'numeric', query: 'invioce 31415', relevant: ['invoice'] },
  {
    id: 'digits-unrelated-word',
    category: 'numeric',
    query: 'invoice 31415 rejected',
    relevant: [],
  },
  {
    id: 'digits-fullwidth',
    category: 'numeric',
    query: 'ｉｎｖｏｉｃｅ ３１４１５',
    relevant: ['invoice'],
  },
  {
    id: 'digits-two',
    category: 'multi-number',
    query: 'release 12 build 34',
    relevant: ['release'],
  },
  {
    id: 'digits-two-reverse',
    category: 'multi-number',
    query: 'release 34 build 12',
    relevant: ['release-reverse'],
  },
  { id: 'digits-two-absent', category: 'multi-number', query: 'release 12 build 36', relevant: [] },
  {
    id: 'digits-repeated',
    category: 'multi-number',
    query: 'release 12 build 12',
    relevant: ['release-repeat'],
  },
  {
    id: 'digits-pair',
    category: 'multi-number',
    query: '12 34',
    relevant: ['release', 'release-reverse'],
  },
  { id: 'ticket-exact', category: 'identifier', query: 'INC-742', relevant: ['ticket'] },
  { id: 'ticket-prefix', category: 'identifier', query: 'INC-74', relevant: [] },
  { id: 'ticket-natural', category: 'identifier', query: '障害 INC-742', relevant: ['ticket'] },
  { id: 'ticket-width', category: 'identifier', query: 'ＩＮＣ－７４２', relevant: ['ticket'] },
  { id: 'year-width', category: 'numeric', query: '2026', relevant: ['year'] },
  { id: 'year-natural', category: 'numeric', query: '2026年度の検索品質', relevant: ['year'] },
  { id: 'decimal', category: 'multi-number', query: '3.14', relevant: ['decimal'] },
  { id: 'decimal-absent', category: 'multi-number', query: '3.1', relevant: [] },
  { id: 'leading-zero', category: 'numeric', query: '007', relevant: ['leading-zero'] },
  { id: 'plain-seven', category: 'numeric', query: '7', relevant: ['plain-seven'] },
  {
    id: 'multi-enabled',
    category: 'multiword',
    query: 'ActivityPub enabled',
    relevant: ['activity'],
  },
  {
    id: 'multi-disabled',
    category: 'multiword',
    query: 'ActivityPub disabled',
    relevant: ['disabled'],
  },
  {
    id: 'multi-reordered',
    category: 'multiword',
    query: 'enabled ActivityPub',
    relevant: ['activity'],
  },
  { id: 'negative-or', category: 'negative', query: 'absent OR ActivityPub', relevant: [] },
  { id: 'negative-not', category: 'negative', query: 'not ActivityPub', relevant: [] },
  { id: 'negative-term', category: 'negative', query: 'ActivityPub blackhole', relevant: [] },
  { id: 'negative-ja', category: 'negative', query: '図書館 閉鎖', relevant: [] },
  { id: 'negative-unrelated', category: 'negative', query: '天文学', relevant: [] },
  {
    id: 'unicode-combining',
    category: 'unicode',
    query: 'カ\u3099ラス',
    relevant: ['glass', 'unicode'],
  },
  { id: 'unicode-composed', category: 'unicode', query: 'café', relevant: ['unicode'] },
  { id: 'unicode-ligature', category: 'unicode', query: '1 api ffi', relevant: ['width'] },
  { id: 'unicode-width', category: 'unicode', query: 'ＡＰＩ', relevant: ['width'] },
  { id: 'unicode-emoji', category: 'unicode', query: '🧑‍💻', relevant: ['unicode'] },
  { id: 'unicode-accent', category: 'unicode', query: 'résumé', relevant: ['accent'] },
  { id: 'unicode-trim', category: 'unicode', query: '\uFEFF\tＡＰＩ\u3000', relevant: ['width'] },
  { id: 'percent', category: 'escaping', query: '%', relevant: ['escape'] },
  { id: 'underscore', category: 'escaping', query: '_', relevant: ['escape', 'identifier'] },
  { id: 'backslash', category: 'escaping', query: '\\', relevant: ['escape'] },
  { id: 'literal-percent', category: 'escaping', query: '50%', relevant: ['escape'] },
  { id: 'literal-underscore', category: 'escaping', query: 'x_y', relevant: ['escape'] },
  { id: 'literal-path', category: 'escaping', query: 'C:\\tmp', relevant: ['escape'] },
  { id: 'sql-injection', category: 'escaping', query: "' OR 1=1 --", relevant: [] },
  { id: 'url', category: 'identifier', query: 'example.test/team/repo-name', relevant: ['url'] },
  { id: 'hyphen', category: 'identifier', query: 'alpha-beta', relevant: ['identifier'] },
  {
    id: 'identifier-underscore',
    category: 'identifier',
    query: 'user_id',
    relevant: ['identifier'],
  },
];

/** Fixed competing semantic rankings: controlled inputs, not a claim about embedding model quality. */
export const qualityHybridCases = [
  {
    id: 'numeric-competition',
    queryId: 'digits-natural',
    semantic: [
      'invoice-neighbor',
      'invoice-prefix',
      'invoice-suffix',
      'invoice-short',
      'unrelated',
    ],
    required: ['invoice'],
  },
  {
    id: 'numeric-typo-competition',
    queryId: 'digits-natural-typo',
    semantic: [
      'invoice-neighbor',
      'invoice-prefix',
      'invoice-suffix',
      'invoice-short',
      'unrelated',
    ],
    required: ['invoice'],
  },
  {
    id: 'ticket-competition',
    queryId: 'ticket-exact',
    semantic: ['ticket-neighbor', 'ticket-long', 'unrelated', 'year', 'search'],
    required: ['ticket'],
  },
  { id: 'typo-keyword-only', queryId: 'latin-typo', semantic: [], required: ['nebula'] },
  { id: 'ja-typo-keyword-only', queryId: 'ja-typo', semantic: [], required: ['glass', 'unicode'] },
  {
    id: 'multi-consensus',
    queryId: 'multi-enabled',
    semantic: ['disabled', 'activity', 'unrelated', 'nebula', 'search'],
    required: ['activity'],
  },
  {
    id: 'unicode-consensus',
    queryId: 'unicode-composed',
    semantic: ['accent', 'unicode', 'glass', 'unrelated', 'cat'],
    required: ['unicode'],
  },
  { id: 'escaping-keyword-only', queryId: 'literal-percent', semantic: [], required: ['escape'] },
] as const;
